-- Table: t_billing_header
-- Core Billing Table (Created by Payment Sync Module if missing)
CREATE TABLE IF NOT EXISTS public.t_billing_header (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_masa integer DEFAULT 20241,
    nim character(9) DEFAULT '123456789',
    nobilling character varying(255),
    id_sumber_data integer,
    id_jenis_bayar smallint,
    tanggalsetor date,
    totalsks integer,
    totalbayar numeric(18,2),
    id_status_billing smallint,
    cabangbank character varying(100),
    tanggalregistrasi date,
    id_status_terbayar smallint DEFAULT 0,
    id_mitra_transaksi smallint,
    id_status_paket smallint,
    nomorviraccount character(20),
    last_modified date,
    created_by character varying(100),
    updated_by character varying(100),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    id_cmhs integer,
    id_mhs integer,
    waktu_pembayaran timestamp without time zone,
    masa character(5),
    CONSTRAINT t_billing_header_pkey PRIMARY KEY (id)
);

-- Table: t_payment_patterns
-- Stores Regex patterns for extracting billing numbers from bank remarks.
CREATE TABLE public.t_payment_patterns (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pattern_name character varying(100) NOT NULL,
    regex_pattern text NOT NULL,
    description text,
    is_active boolean DEFAULT true NOT NULL,
    priority integer DEFAULT 0 NOT NULL,
    created_by character varying(100),
    updated_by character varying(100),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    CONSTRAINT t_payment_patterns_pkey PRIMARY KEY (id)
);

-- Table: t_bank_mutasi
-- Staging table for raw bank transactions (BRI Bank Statement).
CREATE TABLE public.t_bank_mutasi (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    reference_no character varying(100) NOT NULL, -- Unique ID from Bank
    account_no character varying(50),
    trx_date timestamp without time zone NOT NULL,
    journal_seq character varying(50),
    amount numeric(18,2) NOT NULL,
    description text, -- Raw Remark from Bank
    id_billing_header bigint, -- Nullable FK to t_billing_header
    status character varying(20) DEFAULT 'NEW'::character varying NOT NULL, -- NEW, PROCESSED, UNIDENTIFIED, SUSPICIOUS
    processing_log text, -- Captures error messages or processing details
    created_by character varying(100),
    updated_by character varying(100),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    CONSTRAINT t_bank_mutasi_pkey PRIMARY KEY (id),
    CONSTRAINT t_bank_mutasi_ref_unique UNIQUE (reference_no)
);

-- Index for faster lookup by status (Worker Queue)
CREATE INDEX idx_bank_mutasi_status ON public.t_bank_mutasi (status) WHERE deleted_at IS NULL;
-- Index for finding duplicates by reference
CREATE INDEX idx_bank_mutasi_ref ON public.t_bank_mutasi (reference_no);

-- Trigger Function: Update timestamps automatically
CREATE OR REPLACE FUNCTION public.update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply Triggers
CREATE TRIGGER trigger_update_timestamp_t_payment_patterns
BEFORE UPDATE ON public.t_payment_patterns
FOR EACH ROW EXECUTE PROCEDURE public.update_timestamp();

CREATE TRIGGER trigger_update_timestamp_t_bank_mutasi
BEFORE UPDATE ON public.t_bank_mutasi
FOR EACH ROW EXECUTE PROCEDURE public.update_timestamp();
